### ISSUE TITLE
ModuleNotFoundError: No module named 'matplotlib'

### ISSUE THREAD

**Issue by joacorapela** [sphinx-gallery/sphinx-gallery#1049]
I am trying to deploy my sphinx-gallery (SG) to my GitHub pages using GitHub actions. When my GitHub action runs I get the following error:

> Exception occurred:
>   File "/usr/local/lib/python3.8/site-packages/sphinx_gallery/scrapers.py", line 39, in _import_matplotlib
>     import matplotlib
> ModuleNotFoundError: No module named 'matplotlib'
> The full traceback has been saved in /tmp/sphinx-err-tyuu1nd6.log, if you want to report the issue to the developers.
> Please also report this if it was a user error, so that a better error message can be provided next time.
> A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

When I build my SG locally, with `make html`, everything works well. I only experience problems in the previous deployment. I explicitly included `matplotlib` in the dependencies of my workflow. Here is my workflow file:

```
name: docs
on: [push, pull_request, workflow_dispatch]
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          pip install matplotlib
          pip install -e .[notebook,docs]
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/sphinx"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/sphinx/build/html
          force_orphan: true
```

I am not sure if this is a GitHub action or a SG problem. I would greatly appreciate any hint.

Cordially, Joaquin
