### ISSUE TITLE
Distorted gallery overview

### ISSUE THREAD

**Issue by nicrie** [sphinx-gallery/sphinx-gallery#918]
Really great package, I love the python script integration to create automated examples! 

It seems though that I'm doing something wrong although I'm not sure what exactly. When I build the example gallery for my [package](https://github.com/nicrie/xeofs) on readthedocs, the [overview gallery](https://xeofs.readthedocs.io/en/latest/auto_examples/index.html) somehow gets distorted.

I hope it is not related to the [sphinx awesome theme](https://sphinxawesome.xyz/) I currently use, since I'm quite happy with it. 
Do you have any idea what could be the problem in my case?

**Comment by larsoner** [comment]
Can you try latest `master`? It's possible that https://github.com/sphinx-gallery/sphinx-gallery/pull/914 fixed this because there was a missing `</div>` I think

**Comment by nicrie** [comment]
Thanks for the suggesting! I just tried but to no avail. Here's what I specified in the `environment.yml` for readthedocs:

``` yml
name: xeofs
channels:
  - conda-forge
  - defaults
dependencies:
  - python>3.8
  - numpy
  - pandas
  - xarray
  - conda
  - scikit-learn
  - yaml
  - matplotlib
  - seaborn
  - pip:
    - sphinxawesome-theme
    - git+https://github.com/sphinx-gallery/sphinx-gallery.git@master
    - xeofs
```

What did change though is that the titles of the individual examples appeared. They were also shown as hyperlinks before, but it looked wrong to me. Now they are shown twice, but the "new" titles have a better optic, so I guess the current `master` did indeed help solve something! ;)
